### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by till** [flatcar/flatcar-mastodon#2]
I have good experience with pgbackrest and barman. They use the wal to backup continuously. No pgdump necessary.

Could allow for putting backups into an s3 compatible store. Maybe even ease restore when moving between hardware/providers.

**Comment by t-lo** [comment]
Hmmm, this approach seems very interesting and would likely suit long-lived nodes better than what I'm currently working on. My own approach is more focused on bringing up a hot spare and switching over (direct node-to-node backup).

I feel there's room for both - would you be interested in taking a stab?

**Comment by till** [comment]
Not sure. How would you propose I go about that?

**Comment by t-lo** [comment]
Not exactly sure since I'm not familiar with these tools :)
Is there a docker container available for this which we could wire to mastodon's postgres? This way it would work for this project as well as for others.

**Comment by t-lo** [comment]
Implemented in https://github.com/flatcar/flatcar-mastodon/pull/6  - including a mechanism to move to a different node ("node cloning"), e.g. a different provider or instance size.

@till I'll close this issue for now. Backup/restore and node migration details are https://github.com/flatcar/flatcar-mastodon#backup-and-restore-node-cloning-and-vertical-scaling, please let me know what you think!
