### ISSUE TITLE
[RFE] Monitoring

### ISSUE THREAD

**Issue by t-lo** [flatcar/flatcar-mastodon#3]
## Current situation

No monitoring except for what Mastodon ships (pghero and sidekiq dashboards). No alerting.

## Impact

Very limited insight in what's going on on the node. No email / otherwise alerts in potentially critical situations.

## Ideal future situation

Monitoring and alerting are included in the deployment and accessible via HTTPS. Alerting deployment includes sensible defaults, e.g. email alerts to Mastodon admin email address.

## TODO
- [x] Grafana + Prometheus
- [x] Node exporter
- [x] cadvisor
- [x] postgres-exporter
- [x] redis-exporter
- [x] elasticsearch-exporter
- [x] sidekiq-exporter
- [x] mastodon stats exporter

**Comment by meyskens** [comment]
App level monitoring for things like sidekiq is quite essential also. There are solutions like https://github.com/systemli/prometheus-mastodon-exporter and https://github.com/fastly/sidekiq-prometheus

**Comment by t-lo** [comment]
Very good point. Same for postgres https://github.com/prometheus-community/postgres_exporter, redis https://github.com/oliver006/redis_exporter, and elasticsearch https://github.com/prometheus-community/elasticsearch_exporter.
